- id: atSunset
  alias: AtSunset
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: -00:00:00
  action:
    service: scene.turn_on
    entity_id: scene.AtSunset
- id: hourBeforeSunset
  alias: HourBeforeSunset
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: scene.turn_on
    entity_id: scene.hour_before_sunset
- id: atSunrise
  alias: AtSunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:00:00
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.atsunrise
  initial_state: true
- id: StartWaterHeater0600
  alias: Start water heater
  description: Start hot water re-circulator so there is warm water
  trigger:
  - platform: time
    at: 06:00:00
  - platform: state
    entity_id: input_button.hot_water
  - platform: state
    entity_id: binary_sensor.master_bath_toilet_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.master_bath_motion
    to: 'on'
  action:
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.water_heater
  initial_state: true
- id: MasterBathMotionStarts
  alias: Master bath motion starts
  description: Start the hot water timer when there is motion in the bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bath_toilet_motion
    to: 'on'
  action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.water_heater
  initial_state: true
- id: WaterHeaterTimerEnds
  alias: Water Heater timer ends
  description: Turn off the hot water re-circulator when the timer ends
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.water_heater
  action:
  - service: switch.turn_off
    entity_id: switch.water_heater_outlet
  initial_state: true
- id: ClimateEnabled
  alias: Climate Enabled
  description: Turn on heat/air and close the skylight.
  trigger:
  - entity_id: input_boolean.enable_climate
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: climate.central
      hvac_mode: heat_cool
    service: climate.set_hvac_mode
  - data:
      fan_mode: Auto low
    service: climate.set_fan_mode
    target:
      entity_id: climate.central
  - data: {}
    service: cover.close_cover
    target:
      entity_id:
      - cover.master_bath_skylight_switch
      - cover.master_windows
  initial_state: true
  mode: single
- id: ClimateDisabled
  alias: Climate Disabled
  description: Actions taken when the central HVAC is turned off.
  trigger:
  - platform: state
    entity_id: input_boolean.enable_climate
    to: 'off'
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.central
      hvac_mode: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: cool
    target:
      entity_id: climate.master_bedroom
  initial_state: true
  mode: single
- id: Climate_0100
  alias: Climate 0100
  trigger:
  - at: 01:00:00
    platform: time
  action:
  - data:
      entity_id: climate.central
      target_temp_high: 75
      target_temp_low: 62
    service: climate.set_temperature
  initial_state: true
- id: Climate_0600
  alias: Climate 0600
  trigger:
  - at: 06:00:00
    platform: time
  action:
  - data:
      entity_id: climate.central
      target_temp_high: 77
      target_temp_low: 71
    service: climate.set_temperature
  initial_state: true
  mode: single
- id: Climate_2000
  alias: Climate 2000
  trigger:
  - at: '20:00:00'
    platform: time
  action:
  - data:
      target_temp_high: 76
      target_temp_low: 62
    service: climate.set_temperature
    target:
      entity_id: climate.central
  initial_state: true
  mode: single
- id: AtMidnight
  alias: AtMidnight
  initial_state: true
  trigger:
    platform: time
    at: 00:00:00
  action:
    service: scene.turn_on
    entity_id: scene.AtMidnight
- id: At0630
  alias: At0630
  trigger:
  - at: 06:30:00
    platform: time
  action:
  - entity_id: scene.At0630
    service: scene.turn_on
  - data:
      fan_mode: Auto low
    service: climate.set_fan_mode
    target:
      entity_id: climate.central
  initial_state: true
  mode: single
- id: At0800
  alias: At0730
  trigger:
  - at: 07:30:00
    platform: time
  action:
  - entity_id: scene.at0730
    service: scene.turn_on
  initial_state: true
  mode: single
- id: AtNoon
  alias: AtNoon
  initial_state: true
  trigger:
    platform: time
    at: '12:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.AtNoon
- id: At8PM
  alias: At2000
  trigger:
  - at: '20:00:00'
    platform: time
  action:
  - entity_id: scene.At8PM
    service: scene.turn_on
  initial_state: true
  mode: single
- id: AlarmDisarmedDaytime
  alias: 'Alarm: Disarmed Daytime'
  trigger:
  - entity_id: alarm_control_panel.home1
    platform: state
    not_from: unavailable
    to: disarmed
  condition:
  - before: sunset
    condition: sun
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - entity_id: scene.OnDisarmedDaytime
    service: scene.turn_on
  initial_state: true
  mode: single
- id: AlarmDisarmedNighttime
  alias: 'Alarm: Disarmed Nighttime'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home1
    not_from: unavailable
    to: disarmed
  condition:
  - condition: sun
    after: sunset
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.ondisarmednighttime
  initial_state: true
  mode: single
- id: AlarmArmedAway
  alias: 'Alarm: Armed Away'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home1
    not_from: unavailable
    to: armed_away
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id:
      - media_player.sonos_office
      - media_player.sonos_living_room
      - media_player.sonos_kid
      - media_player.master_bedroom_apple_tv
      - media_player.living_room_apple_tv
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    data: {}
    target:
      entity_id:
      - scene.outside_lights_off
      - scene.onarmedaway
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.kitchen_door_lock
  initial_state: true
  mode: single
- id: AlarmArmedStayDaytime
  alias: 'Alarm: Armed Stay Daytime'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home1
    not_from: unavailable
    to: armed_home
  condition:
  - condition: sun
    before: sunset
  action:
  - delay: 120
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.onarmedstaydaytime
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.kitchen_door_lock
  initial_state: true
  mode: single
- id: RainDelayManuallyTriggered
  alias: Rain Delay manually triggered
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.rain_delay
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.rain_delay
- id: RainDelayTimerEnds
  alias: Rain Delay timer ends
  initial_state: true
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.rain_delay
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.rain_delay
- id: kitchenDoorUnlockedArmedAway
  alias: Kitchen Door Unlocked while Armed Away
  trigger:
  - platform: state
    entity_id: lock.kitchen_door_lock
    to: unlocked
  condition:
  - condition: state
    entity_id: alarm_control_panel.home1
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_disarm
    data: {}
    target:
      entity_id: alarm_control_panel.home1
  initial_state: true
  mode: single
- id: KitchenDoorLockedWhileDisarmed
  alias: Kitchen Door Locked while Disarmed
  trigger: []
  condition: []
  action: []
  initial_state: true
  mode: single
- id: DoorbellPushedWhileAway
  alias: Doorbell pushed while away
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.skybell_front_door_button
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.home1
    state: armed_away
  action:
    service: media_player.play_media
    data:
      entity_id: media_player.sonos_living_room
      media_content_id: http://192.168.1.196:8123/local/pitbull.mp3
      media_content_type: music
- id: DoorbellPushedAfterDark
  alias: Doorbell pushed after dark
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.skybell_front_door_button
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.front_entry_light_switch
- id: WaterPlants
  alias: Water Plants
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - wed
      - sat
      before: 00:00:00
    - condition: state
      entity_id: input_boolean.rain_delay
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.WaterPlants
  initial_state: true
- id: WaterFrontLawn
  alias: Water Front Lawn
  trigger:
  - platform: time
    at: 06:32:00
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - wed
      before: 00:00:00
    - condition: state
      entity_id: input_boolean.rain_delay
      state: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.WaterLawn
  initial_state: true
- id: stopAllWatering
  alias: Stop All Watering
  initial_state: true
  trigger:
    platform: time
    at: 06:40:00
  action:
    service: scene.turn_on
    entity_id: scene.StopAllWater
- id: WeeklySoaking
  alias: Weekly Soaking
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - sat
      before: 00:00:00
    - condition: state
      entity_id: input_boolean.rain_delay
      state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.back_drip_switch
  initial_state: true
- id: StopWeeklySoaking
  alias: Stop Weekly Soaking
  initial_state: true
  trigger:
    platform: time
    at: 07:55:00
  action:
    service: scene.turn_on
    entity_id: scene.StopAllWater
- id: KidMotionEnds
  alias: Kid motion ends
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.kid_motion
    to: 'off'
  action:
  - service: timer.start
    entity_id: timer.kid_music
- id: KidMotionStarts
  alias: Kid motion starts
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.kid_motion
    to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.kid_music
- id: KidMusicTimerEnds
  alias: Kid music timer ends
  initial_state: true
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kid_music
  action:
  - service: sonos.set_sleep_timer
    data:
      entity_id: media_player.sonos_kid
      sleep_time: 0
- id: '1625439560442'
  alias: Flag reminder at sunset
  description: Remind users if a flag is outside at sunset.
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: state
    entity_id: input_boolean.flag_outside
    state: 'on'
  action:
  - service: notify.austin
    data:
      message: It's sunset. Bring the flags inside.
      title: Flags are outside at Sunset
  - data:
      delay: 00:00:03
      message: Bring the flags in from the balcony.
      sonos_entity: media_player.sonos_living_room
      volume: 0.5
    service: script.sonos_say
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.flag_outside
    data: {}
  mode: single
- id: '1641445278269'
  alias: Bedtime on button double press
  description: Set the Bedtime scene on double down press of the bedroom light button
  use_blueprint:
    path: IOT_Ninja/zooz-zen30-double-switch-automation-helper.yaml
    input:
      zooz_zen30: dfb6b0948b3864762f67d058c6f4168b
      dimmer_down_2x:
      - service: scene.turn_on
        target:
          entity_id: scene.bedtime
- id: '1641447432195'
  alias: Master Bedroom Lamps multi-tap
  description: Actions to take on multi-tap on master bedroom lamp switch
  use_blueprint:
    path: zooz-zen71-switch-automation-helper.yaml
    input:
      zooz_zen71: 8ae5bcb98b2f8d15e03f7893826481d8
      switch_up_2x:
      - scene: scene.outside_lights_on
      switch_down_2x:
      - scene: scene.bedtime
- id: '1641679319792'
  alias: Garage Lights multi-tap
  description: ''
  use_blueprint:
    path: IOT_Ninja/zooz-zen30-double-switch-automation-helper.yaml
    input:
      zooz_zen30: 1698a955f727fd1348d9cf0404fa5a08
      dimmer_up_2x:
      - scene: scene.outside_lights_on
      dimmer_down_2x:
      - scene: scene.outside_lights_off
- id: '1644087651554'
  alias: Water Heater timer starts
  description: Turn on the hot water re-circulator when the timer starts
  trigger:
  - platform: event
    event_type: timer.started
    event_data:
      entity_id: timer.water_heater
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.water_heater_outlet
  mode: single
- id: '1587841836008'
  alias: Laundry flood
  description: If the laundry floods, announce it on Sonos.
  trigger:
  - entity_id: binary_sensor.laundry_strip_flood
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.adults
    data:
      message: The laundry area is flooded in the master bathroom.
  - data:
      delay: 00:00:03
      message: The laundry area is flooded in the master bathroom.
      sonos_entity: media_player.sonos_office
      volume: 0.5
    service: script.sonos_say
  - delay:
      hours: 0
      minutes: 0
      seconds: 12
      milliseconds: 0
  - data:
      delay: 00:00:03
      message: The laundry area is flooded in the master bathroom.
      sonos_entity: media_player.sonos_living_room
      volume: 0.5
    service: script.sonos_say
  mode: single
- id: AlarmTriggered
  alias: 'Alarm: Triggered'
  description: Actions taken when the Alarm is triggered for any reason (police, medical
    or fire).
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home1
    to: triggered
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.onalarmtriggered
  - service: lock.unlock
    data:
      entity_id: lock.kitchen_door_lock
  - service: notify.adults
    data:
      message: The house alarm has been triggered.
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.master_windows
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.master_blinds
  initial_state: true
  mode: single
- id: RainDelayTurnsOnWhenSkylightSensesRain
  alias: Rain Delay turns on when skylight senses rain
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bath_skylight_flood
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.master_bath_skylight_water_alarm_water_leak_detected_location_provided
    to: 'on'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.rain_delay
  - service: notify.adults
    data:
      message: 'The skylight sensed rain.  Close the windows. '
      title: It's raining!
  - service: cover.close_cover
    data: {}
    target:
      entity_id:
      - cover.master_bath_skylight
      - cover.master_windows
  initial_state: true
  mode: single
- id: '1645831617312'
  alias: Check if car charging when low battery
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.xc90_plug_status
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.xc_90_battery_level
      below: '75'
    - condition: state
      entity_id: device_tracker.volvo_yv4br0cl0n1814975
      state: home
  action:
  - service: notify.austin
    data:
      title: Plug in XC90
      message: It's after 6 and the car battery is low
  mode: single
- id: '1648926796382'
  alias: Kitchen sink flood
  description: If the kitchen sink flood sensor detects water, send a notification
    and announce it on Sonos.
  trigger:
  - entity_id: binary_sensor.kitchen_sink
    platform: state
    to: 'on'
  condition: []
  action:
  - service: notify.adults
    data:
      message: Water leak detected under the kitchen sink.
  - data:
      message: Water leak detected under the kitchen sink.
      sonos_entity: media_player.sonos_office
      volume: 0.5
    service: script.sonos_say
  mode: single
- id: '1655090844282'
  alias: Juicebox charge now if Sparky plugged in
  description: If Sparky is plugged into the Juicebox for 5 minutes, then set Juicebox
    to charge now.  Sparky will not charge until midnight anyways, but will immediately
    honk the horn once there is power available on the charge cable.  We don't want
    that to happen at midnight.
  trigger:
  - platform: state
    entity_id:
    - sensor.charging_status
    to: plugged
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.xc90_plug_status
    state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.charge_now
  mode: single
- id: '1671399805823'
  alias: Disable Master Fan when Heating
  description: Disables the Master Fan when the central HVAC is in heating mode.
  trigger:
  - platform: state
    entity_id:
    - climate.central
    attribute: hvac_action
    to: heating
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.master_bedroom
  mode: single
- id: '1673802978372'
  alias: Close blinds at sunset
  description: Close the master blinds at sunset if the window is already closed.
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: state
    entity_id: cover.master_windows
    state: closed
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.master_blinds
  mode: single
- id: '1676912078084'
  alias: Dinner
  description: Announce dinner on speakers
  trigger:
  - platform: state
    entity_id:
    - input_button.dinner
  condition: []
  action:
  - data:
      delay: 00:00:08
      message: Excuse me ladies and gentlemen, dinner is served.
      sonos_entity: media_player.sonos_office
      volume: 0.5
    service: script.sonos_say
  - data:
      delay: 00:00:08
      message: Excuse me ladies and gentlemen, dinner is served.
      sonos_entity: media_player.sonos_living_room
      volume: 0.5
    service: script.sonos_say
  - data:
      delay: 00:00:08
      message: Excuse me ladies and gentlemen, dinner is served.
      sonos_entity: media_player.sonos_kid
      volume: 0.5
    service: script.sonos_say
  mode: single
