homeassistant:
  # Package support
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy
  ssl_key: !secret ssl_key
  ssl_certificate: !secret ssl_certificate

automation: !include automations.yaml
automation secret: !include automations_with_secret.yaml
config:
discovery:
energy:
frontend:
group: !include groups.yaml
history:
input_button:
logbook: !include logbook.yaml
media_player:
mobile_app:
mqtt: !include mqtt.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sun:
system_health:

# Define logging levels
logger:
  default: info
  logs: 
    # hide 'Updating skybell binary_sensor took longer than the scheduled update interval' messages
    homeassistant.components.skybell.binary_sensor: error
    # debug level for totalconnect
    homeassistant.components.totalconnect: debug
    homeassistant.helpers.entity: error
    homeassistant.core: error
    skybellpy: warn
    
switch:
  - platform: wake_on_lan
    mac: !secret desktop_mac
    name: Desktop

tts:
  - platform: google_translate
    service_name: google_say

input_boolean:
  enable_climate:
    name: Enable Heat/Air
  master_bedroom_shades:
    name: Master Bedroom Shades
    initial: true

#   Rain Delay
# 1) When turned on manually or by automation, an automation starts a timer.
# 2) Lawn watering automation uses it as a condition.
# 3) When the timer completes, it turns off input_boolean.rain_delay
  rain_delay:
    name: Rain Delay
    icon: mdi:water
    initial: false
  flag_outside:
    name: Flag(s) Outside
    initial: false


lovelace:
  mode: yaml

sensor:
  - platform: cert_expiry
    host: ha.mroczek.org
  - platform: cert_expiry
    host: mroczek689154.duckdns.org

timer:
  water_heater:
    duration: '00:10:00'
  rain_delay:
    duration: '96:00:00'
  kid_music:
    duration: '00:05:00'

#volvooncall:
#  username: !secret volvo_username
#  password: !secret volvo_password
#  region: na
