homeassistant:
  # Package support
  packages: !include_dir_named packages

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy
  ssl_key: !secret ssl_key
  ssl_certificate: !secret ssl_certificate

automation: !include automations.yaml
automation secret: !include automations_with_secret.yaml
cover: !include cover.yaml
discovery:
group: !include groups.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
media_player:
notify: !include notifications.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

tts:
  - platform: google_translate
    service_name: google_say

input_boolean:
  enable_climate:
    name: Enable Heat/Air
  master_bedroom_shades:
    name: Master Bedroom Shades
    initial: true

#   Rain Delay
# 1) When turned on manually or by automation, an automation starts a timer.
# 2) Lawn watering automation uses it as a condition.
# 3) When the timer completes, it turns off input_boolean.rain_delay
  rain_delay:
    name: Rain Delay
    icon: mdi:water
    initial: false
  flag_outside:
    name: Flag(s) Outside
    initial: false


lovelace:
  mode: yaml

sensor:
  - platform: cert_expiry
    host: ha.mroczek.org
  - platform: cert_expiry
    host: mroczek689154.duckdns.org
