homeassistant:
  # Name of the location where Home Assistant is running
  name: Mroczek Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Package support
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy
  ssl_key: !secret ssl_key
  ssl_certificate: !secret ssl_certificate

updater:
  include_used_components: true

system_health:

# Discover some devices automatically
discovery:
  ignore:
    - sonos

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude: 
    entities:
      - binary_sensor.master_bedroom_motion
      - binary_sensor.master_bath_motion
      - binary_sensor.melanie_motion
      - binary_sensor.master_bath_toilet_motion
      - sensor.master_bath_light_burglar
      - sensor.master_bath_toilet_burglar
      - switch.master_bedroom_thermostat_switch
    domains:
      - automation
      - sun
      - timer
      - zwave


# Define logging levels
logger:
  default: info
  logs: 
    # hide 'Updating skybell binary_sensor took longer than the scheduled update interval' messages
    homeassistant.components.binary_sensor: error
    # hide 'Could not connect' errors when plex server is turned off for power savings
    homeassistant.components.plex: fatal
    homeassistant.components.plex.media_player: fatal
    homeassistant.components.media_player.plex: fatal
    homeassistant.helpers.entity: error
    homeassistant.core: error
    skybellpy: warn
    
zwave:
  usb_path: /dev/ttyAMA0
  autoheal: false
  network_key: !secret zwave_network_key

media_player:
#  - platform: roku
#    name: Roku Master Bedroom
#    host: !secret roku_master_bedroom_ip
#  - platform: roku
#    name: Roku Living Room
#    host: !secret roku_living_room_ip
#  - platform: roku
#    name: Roku Studio
#    host: !secret roku_studio_ip

roku:
  - host: !secret roku_master_bedroom_ip
  - host: !secret roku_living_room_ip
  - host: !secret roku_studio_ip

sonos:
  media_player:
    hosts:
      - !secret sonos_living_room_ip
      - !secret sonos_master_bedroom_ip
      - !secret sonos_kid_bedroom_ip

# docs at https://home-assistant.io/components/skybell/
skybell:
  username: !secret skybell_username
  password: !secret skybell_password

binary_sensor:
  - platform: skybell
    monitored_conditions:
      - button
      - motion

camera:
  - platform: skybell

switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb
      - motion_sensor


group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
sun:

tts:
  - platform: google_translate
    service_name: google_say
    base_url: !secret tts_url

input_boolean:
  enable_climate_heat:
    name: Enable Heat
  enable_climate_air:
    name: Enable Air
  master_bedroom_shades:
    name: Master Bedroom Shades
    initial: true

#   Rain Delay
# 1) When turned on manually or by automation, an automation starts a timer.
# 2) Lawn watering automation uses it as a condition.
# 3) When the timer completes, it turns off input_boolean.rain_delay
  rain_delay:
    name: Rain Delay
    icon: mdi:water
    initial: false

lovelace:
  mode: yaml

mqtt:
  broker: !secret mqtt_broker_address

mychevy:
  username: !secret mychevy_username
  password: !secret mychevy_password

sensor:
  - platform: cert_expiry
    host: ha.mroczek.org
  - platform: cert_expiry
    host: mroczek689154.duckdns.org

timer:
  water_heater:
    duration: '00:05:00'
  rain_delay:
    duration: '96:00:00'

totalconnect:
  username: !secret totalconnect_username
  password: !secret totalconnect_password
