homeassistant:
  # Name of the location where Home Assistant is running
  name: Mroczek Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Package support
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

updater:
  include_used_components: true

system_health:

# Discover some devices automatically
discovery:
  ignore:
    - sonos
    - roku

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Define logging levels
logger:
  default: info
  logs: 
    # hide 'Updating skybell binary_sensor took longer than the scheduled update interval' messages
    homeassistant.components.binary_sensor: error
    # hide 'Could not connect' errors when plex server is turned off for power savings
    homeassistant.components.plex: fatal
    homeassistant.components.media_player.plex: fatal
    homeassistant.helpers.entity: error
    homeassistant.core: error
    skybellpy: warn
    
zwave:
  usb_path: /dev/ttyAMA0
  autoheal: false
  network_key: !secret zwave_network_key

media_player:
  - platform: roku
    name: Roku Master Bedroom
    host: !secret roku_master_bedroom_ip
  - platform: roku
    name: Roku Living Room
    host: !secret roku_living_room_ip
  - platform: roku
    name: Roku Studio
    host: !secret roku_studio_ip

roku:
  - host: !secret roku_master_bedroom_ip
  - host: !secret roku_living_room_ip
  - host: !secret roku_studio_ip

sonos:
  media_player:
    hosts:
      - !secret sonos_living_room_ip
      - !secret sonos_master_bedroom_ip
      - !secret sonos_kid_bedroom_ip

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  exclude:
    domains:
      - sun
      - openweathermap
    entities:
      - sensor.melanie_dimmer_alarm_level
      - sensor.melanie_dimmer_alarm_type_2
      - sensor.melanie_dimmer_alarm_type
      - sensor.melanie_dimmer_alarm_level_2
      - sensor.melanie_dimmer_burglar
      - sensor.melanie_dimmer_burglar_2
      - sensor.melanie_dimmer_sourcenodeid
      - sensor.melanie_dimmer_sourcenodeid_2
      - sensor.kitchen_door_light_previous_energy
      - sensor.master_bath_alarm_level
      - sensor.master_bath_alarm_level_2
      - sensor.master_bath_alarm_type
      - sensor.master_bath_alarm_type_2
      - sensor.master_bath_burglar
      - sensor.master_bath_burglar_2
      - sensor.master_bath_sourcenodeid
      - sensor.master_bath_sourcenodeid_2
      - sensor.master_bedroom_sensor_alarm_level
      - sensor.master_bedroom_sensor_alarm_type
      - sensor.master_bedroom_sensor_burglar
      - sensor.master_bedroom_sensor_sourcenodeid
      - sensor.master_bedroom_sensor_ultraviolet
      - sensor.mychevy_2016_chevrolet_spark_ev_charge_mode
      - sensor.owm_condition
      - sensor.owm_cloud_coverage
      - sensor.owm_humidity
      - sensor.owm_rain
      - sensor.owm_temperature

tts:
  - platform: google_translate
    service_name: google_say

notify:
  - name: mroczek_email
    platform: smtp
    sender: !secret smtp_sender
    recipient: !secret smtp_recipient
    server: !secret smtp_server
    port: !secret smtp_port
    username: !secret smtp_username
    password: !secret smtp_password
    encryption: !secret smtp_encryption

lovelace:
  mode: yaml

mychevy:
  username: !secret mychevy_username
  password: !secret mychevy_password
