homeassistant:
  # Name of the location where Home Assistant is running
  name: Mroczek Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Package support
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy
  ssl_key: !secret ssl_key
  ssl_certificate: !secret ssl_certificate

updater:

system_health:

# Discover some devices automatically
discovery:
  ignore:
    - sonos

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude: 
    entities:
      - binary_sensor.master_bedroom_motion
      - binary_sensor.master_bath_motion
      - binary_sensor.kid_motion
      - binary_sensor.master_bath_toilet_motion
      - sensor.master_bath_light_burglar
      - sensor.master_bath_toilet_burglar
      - switch.master_bedroom_thermostat_switch
    domains:
      - automation
      - sun
      - timer
      - zwave


# Define logging levels
logger:
  default: info
  logs: 
    # hide 'Updating skybell binary_sensor took longer than the scheduled update interval' messages
    homeassistant.components.binary_sensor: error
    # hide 'Could not connect' errors when plex server is turned off for power savings
    homeassistant.components.plex: fatal
    homeassistant.components.plex.media_player: fatal
    homeassistant.components.media_player.plex: fatal
    homeassistant.helpers.entity: error
    homeassistant.core: error
    skybellpy: warn
    
media_player:

sonos:
  media_player:
    hosts:
      - !secret sonos_living_room_ip
      - !secret sonos_master_bedroom_ip
      - !secret sonos_kid_bedroom_ip

# docs at https://home-assistant.io/components/skybell/
skybell:
  username: !secret skybell_username
  password: !secret skybell_password

binary_sensor:
  - platform: skybell
    monitored_conditions:
      - button
      - motion
  - platform: template
    sensors:
      fish_cold:
        friendly_name: "Fish Tank is Cold"
        device_class: cold
        value_template: "{{ states('sensor.fish_temperature')|float < 72 }}"
      fish_hot:
        friendly_name: "Fish Tank is Hot"
        device_class: heat
        value_template: "{{ states('sensor.fish_temperature')|float > 75 }}"
  - platform: mqtt
    name: YouTube
    state_topic: "ha/internet/youtube"
    device_class: connectivity
    availability:
      - topic: "ha/internet/youtube/available"

camera:
  - platform: skybell

switch:
  - platform: skybell
    monitored_conditions:
      - do_not_disturb
      - motion_sensor
# see https://github.com/austinmroczek/mqtt-control-openwrt
  - platform: mqtt
    unique_id: kid_internet
    name: Kid Internet
    state_topic: "ha/internet/kid_computer"
    command_topic: "ha/internet/kid_computer"
    retain: true
    availability:
      - topic: "ha/internet/kid_computer/available"
  - platform: mqtt
    unique_id: ipad_internet
    name: iPad Internet
    state_topic: "ha/internet/ipad"
    command_topic: "ha/internet/ipad"
    retain: true
    availability:
      - topic: "ha/internet/ipad/available"
  - platform: mqtt
    unique_id: guest_roku_internet
    name: Guest Roku Internet
    state_topic: "ha/internet/roku"
    command_topic: "ha/internet/roku"
    retain: true
    availability:
      - topic: "ha/internet/roku/available"
  - platform: wake_on_lan
    mac: !secret desktop_mac
    name: Desktop

automation: !include automations.yaml
automation secret: !include automations_with_secret.yaml
group: !include groups.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sun:

tts:
  - platform: google_translate
    service_name: google_say
    base_url: !secret tts_url

input_boolean:
  enable_climate:
    name: Enable Heat/Air
  master_bedroom_shades:
    name: Master Bedroom Shades
    initial: true

#   Rain Delay
# 1) When turned on manually or by automation, an automation starts a timer.
# 2) Lawn watering automation uses it as a condition.
# 3) When the timer completes, it turns off input_boolean.rain_delay
  rain_delay:
    name: Rain Delay
    icon: mdi:water
    initial: false
  flag_outside:
    name: Flag(s) Outside
    initial: false


lovelace:
  mode: yaml

mqtt:
  broker: !secret mqtt_broker_address

mychevy:
  username: !secret mychevy_username
  password: !secret mychevy_password

sensor:
  - platform: cert_expiry
    host: ha.mroczek.org
  - platform: cert_expiry
    host: mroczek689154.duckdns.org

timer:
  water_heater:
    duration: '00:05:00'
  rain_delay:
    duration: '96:00:00'
  kid_music:
    duration: '00:05:00'

webostv:
  host: !secret master_tv_address
  name: Master Bedroom TV
