title: Mroczek Home
views:
  - title: Main
    cards:
      - type: entities
        title: Main
        entities:
          - alarm_control_panel.home1
          - lock.kitchen_door_lock
          - sensor.hall_temperature
          - sensor.master_bedroom_sensor_temperature
          - input_boolean.enable_climate_air
          - input_boolean.enable_climate_heat

      - type: conditional
        conditions:
          - entity: input_boolean.enable_climate_air
            state: "on"
        card:
          type: thermostat
          entity: climate.cooling
          name: Central Air
      - type: conditional
        conditions:
          - entity: input_boolean.enable_climate_heat
            state: "on"
        card:
          type: thermostat
          entity: climate.heating
          name: Central Heat

      - type: weather-forecast
        entity: weather.openweathermap


  - title: Downstairs
    cards:
      - type: entities
        title: Entry
        entities:
          - camera.front_door
          - switch.front_entry_light_switch
          - switch.front_porch_switch
      - type: entities
        title: Kitchen
        entities:
          - switch.kitchen_switch
          - lock.kitchen_door_lock
          - sensor.kitchen_door_lock_power_management_2
      - type: entities
        title: Other
        entities:
          - light.hall_level
          - switch.stairway_switch
          - group.fish
          - light.dining_room_level
          - switch.desktop
      - type: conditional
        conditions:
          - entity: media_player.roku_living_room
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.roku_living_room
      - type: media-control
        entity: media_player.sonos_living_room
      - type: entities
        title: Melanie
        entities:
          - light.melanie
          - binary_sensor.melanie_motion
      - type: media-control
        entity: media_player.sonos_melanie

  - title: Upstairs
    cards:
      - type: entities
        title: Master Bedroom
        entities:
          - sensor.master_bedroom_sensor_relative_humidity
          - sensor.master_bedroom_sensor_luminance
          - sensor.master_bedroom_sensor_temperature
          - binary_sensor.master_bedroom_motion
          - fan.master_fan_level
          - switch.master_lights_switch_2
          - switch.master_lights_switch_3
          - cover.master_blinds
      - type: entities
        title: Master Bath
        entities:
          - light.master_bath_level
          - binary_sensor.master_bath_motion
      - type: conditional
        conditions:
          - entity: media_player.roku_master_bedroom
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.roku_master_bedroom
      - type: media-control
        entity: media_player.sonos_master_bedroom








  - title: Outside
    cards:
      - type: entities
        title: Garage
        entities:
          - switch.garage_lights_switch_2
          - switch.garage_lights_switch_3
          - input_boolean.laundry
          - timer.laundry
      - type: entities
        title: Sparky
        entities:
          - binary_sensor.mychevy_2016_chevrolet_spark_ev_plugged_in
          - sensor.mychevy_2016_chevrolet_spark_ev_battery_level
          - sensor.mychevy_2016_chevrolet_spark_ev_charge_mode
          - sensor.mychevy_2016_chevrolet_spark_ev_charged_by
          - sensor.mychevy_2016_chevrolet_spark_ev_electric_range
          - sensor.mychevy_2016_chevrolet_spark_ev_mileage
          - sensor.mychevy_status
      - type: entities
        title: Sprinklers
        entities:
          - switch.back_drip_switch
          - switch.front_drip_switch
          - switch.front_lawn_switch
          - switch.side_drip_switch
          - input_boolean.rain_delay
          - timer.rain_delay
      - type: entities
        title: Lights
        entities:
          - switch.back_floodlights_switch
          - switch.kitchen_door_light_switch
          - switch.front_patio_switch_2
          - switch.front_entry_light_switch
          - switch.front_porch_switch
          - timer.front_patio_motion_timer
      - type: entities
        title: Weather
        entities:
          - sun.sun
          - sensor.owm_cloud_coverage
          - sensor.owm_condition
          - sensor.owm_humidity
          - sensor.owm_rain
          - sensor.owm_temperature
      - type: entities
        title:  Water Heater
        entities:
          - switch.water_heater_outlet 
 

  - title: Door
    cards:
      - type: entities
        title: Kitchen Door
        entities:
          - group.door_keypad_1
          - group.door_keypad_2
          - group.door_keypad_3
          - group.door_keypad_4
          - group.door_keypad_5
          - group.door_keypad_6
          - group.door_keypad_7
          - group.door_keypad_8
          - group.door_keypad_9
          - group.door_keypad_10
          - group.door_keypad_11
          - group.door_keypad_12
          - group.door_keypad_13
          - group.door_keypad_14
          - group.door_keypad_15
          - group.door_keypad_16
          - group.door_keypad_17
          - group.door_keypad_18

