title: Mroczek Home
views:
  - title: Main
    cards:
      - type: entities
        title: Main
        entities:
          - alarm_control_panel.home1
          - group.internet
          - sensor.hall_temperature
          - sensor.master_bedroom_temperature
          - input_button.hot_water
          - input_boolean.enable_climate
          - input_boolean.flag_outside
          - scene.bedtime
          - scene.showtime
      - type: conditional
        conditions:
          - entity: input_boolean.enable_climate
            state: "on"
        card:
          type: thermostat
          entity: climate.central
          name: Central Heat/Air
      - type: weather-forecast
        entity: weather.openweathermap

  - title: Cars
    cards:
      - type: entities
        title: JuiceBox Charger
        entities:
          - switch.charge_now
          - sensor.charging_status
      - type: entities
        title: Bessie
        entities:
          - binary_sensor.xc90_plug_status
          - binary_sensor.xc90_battery_charging
          - sensor.xc_90_battery_level




  - title: Downstairs
    cards:
      - type: entities
        title: Entry
        entities:
          - camera.front_door
          - switch.front_entry_light_switch
          - switch.front_porch_switch
      - type: entities
        title: Kitchen
        entities:
          - switch.kitchen_lights
          - lock.kitchen_door_lock
          - sensor.kitchen_door_lock_battery
      - type: entities
        title: Living Room
        entities:
          - switch.piano_outlet_switch
          - media_player.living_room_apple_tv


      - type: entities
        title: Other
        entities:
          - switch.hall
          - switch.stairway_switch
          - light.dining_room_level
          - switch.desktop
      - type: media-control
        entity: media_player.living_room_apple_tv
      - type: media-control
        entity: media_player.sonos_living_room
      - type: entities
        title: Kid
        entities:
          - light.kid_light
          - group.internet
          - binary_sensor.kid_motion
      - type: media-control
        entity: media_player.sonos_kid

  - title: Upstairs
    cards:
      - type: entities
        title: Master Bedroom
        entities:
          - cover.master_windows
          - cover.master_blinds
          - sensor.master_bedroom_sensor_relative_humidity
          - sensor.master_bedroom_sensor_luminance
          - sensor.master_bedroom_temperature
          - binary_sensor.master_bedroom_motion
          - fan.master_fan_level
          - switch.master_bedroom_lamps
          - switch.master_fan_light
          - light.master_bedroom
          - climate.master_bedroom
          - media_player.master_bedroom_apple_tv
      - type: entities
        title: Master Bath
        entities:
          - light.master_bath_light
          - light.master_bath_sink
          - light.master_bath_vanity
          - light.master_bath_shower
          - light.master_bath_tub
          - light.master_bath_toilet_light
          - switch.master_laundry_plug
          - binary_sensor.master_bath_motion
          - cover.master_bath_skylight
      - type: media-control
        entity: media_player.sonos_master_bedroom
      - type: media-control
        entity: media_player.master_bedroom_apple_tv

  - title: Outside
    cards:
      - type: entities
        title: Garage
        entities:
          - light.garage_front
          - switch.garage_lights
      - type: entities
        title: Sprinklers
        entities:
          - switch.back_drip_switch
          - switch.front_drip
          - switch.front_lawn
          - switch.side_drip_switch
          - input_boolean.rain_delay
          - timer.rain_delay
          - scene.stopallwater
      - type: entities
        title: Lights
        entities:
          - switch.back_floodlights_switch
          - switch.back_balcony_lights
          - switch.kitchen_door
          - switch.front_patio
          - switch.front_entry_light_switch
          - switch.front_porch_switch
      - type: entities
        title: Current Weather
        entities:
          - sun.sun
          - sensor.openweathermap_cloud_coverage
          - sensor.openweathermap_condition
          - sensor.openweathermap_humidity
          - sensor.openweathermap_rain
          - sensor.openweathermap_temperature
      - type: entities
        title:  Water Heater
        entities:
          - switch.water_heater_outlet 

