blueprint:
  name: Zooz ZEN30
  description: Automations helper for the Zooz ZEN30 Double Switch using the Zwave
    JS integration.
  domain: automation
  input:
    zooz_zen30:
      name: Zooz ZEN30
      description: The ZEN30 Double Switch to interact with.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN30
    dimmer_up_1x:
      name: Top Paddle 1x
      description: 'Action to run on dimmer upper paddle single tap. Default: Turn
        on dimmer switch load to last/custom brightness.'
      default: []
      selector:
        action: {}
    dimmer_up_2x:
      name: Top Paddle 2x
      description: Action to run on dimmer upper paddle double tap.
      default: []
      selector:
        action: {}
    dimmer_up_3x:
      name: Top Paddle 3x
      description: 'Action to run on dimmer upper paddle triple tap. Default: Enter
        inclusion/pairing mode.'
      default: []
      selector:
        action: {}
    dimmer_up_4x:
      name: Top Paddle 4x
      description: Action to run on dimmer upper paddle quadruple tap.
      default: []
      selector:
        action: {}
    dimmer_up_5x:
      name: Top Paddle 5x
      description: Action to run on dimmer upper paddle quintuple tap.
      default: []
      selector:
        action: {}
    dimmer_up_hold:
      name: Top Paddle Hold
      description: 'Action to run on dimmer upper paddle press-and-hold. Default:
        Increase dimmer brightness level.'
      default: []
      selector:
        action: {}
    dimmer_up_release:
      name: Top Paddle Release
      description: Action to run on dimmer upper paddle release.
      default: []
      selector:
        action: {}
    dimmer_down_1x:
      name: Lower Paddle 1x
      description: 'Action to run on dimmer lower paddle single tap. Default: Turn
        off dimmer switch load.'
      default: []
      selector:
        action: {}
    dimmer_down_2x:
      name: Lower Paddle 2x
      description: Action to run on dimmer lower paddle double tap.
      default: []
      selector:
        action: {}
    dimmer_down_3x:
      name: Lower Paddle 3x
      description: 'Action to run on dimmer lower paddle triple tap. Default: Enter
        exclusion/un-pairing mode.'
      default: []
      selector:
        action: {}
    dimmer_down_4x:
      name: Lower Paddle 4x
      description: Action to run on dimmer lower paddle quadruple tap.
      default: []
      selector:
        action: {}
    dimmer_down_5x:
      name: Lower Paddle 5x
      description: Action to run on dimmer lower paddle quintuple tap.
      default: []
      selector:
        action: {}
    dimmer_down_hold:
      name: Bottom Paddle Hold
      description: 'Action to run on dimmer lower paddle press-and-hold. Default:
        Decrease dimmer brightness level.'
      default: []
      selector:
        action: {}
    dimmer_down_release:
      name: Bottom Paddle Release
      description: Action to run on dimmer lower paddle double tap.
      default: []
      selector:
        action: {}
    relay_1x:
      name: Relay 1x
      description: 'Action to run on relay button single tap. Default: Toggle relay
        switch load.'
      default: []
      selector:
        action: {}
    relay_2x:
      name: Relay 2x
      description: Action to run on relay button double tap.
      default: []
      selector:
        action: {}
    relay_3x:
      name: Relay 3x
      description: 'Action to run on relay button triple tap. Default: Enter inclusion/pairing
        mode.'
      default: []
      selector:
        action: {}
    relay_4x:
      name: Relay 4x
      description: Action to run on relay button quadruple tap.
      default: []
      selector:
        action: {}
    relay_5x:
      name: Relay 5x
      description: Action to run on relay button quintuple tap.
      default: []
      selector:
        action: {}
    relay_hold:
      name: Relay Hold
      description: 'Action to run on relay button press-and-hold. Default: Increase
        dimmer brightness level.'
      default: []
      selector:
        action: {}
    relay_release:
      name: Relay Release
      description: Action to run on relay button release.
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/zooz-zen30-double-switch-automation-helper/281362
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: zwave_js_value_notification
  event_data:
    command_class_name: Central Scene
    device_id: !input 'zooz_zen30'
action:
- variables:
    scene_id: '{{ trigger.event.data.label }}'
    attribute_id: '{{ trigger.event.data.value }}'
- choose:
  - conditions: '{{ scene_id == ''Scene 001'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_id == ''KeyPressed'' }}'
        sequence: !input 'dimmer_up_1x'
      - conditions: '{{ attribute_id == ''KeyPressed2x'' }}'
        sequence: !input 'dimmer_up_2x'
      - conditions: '{{ attribute_id == ''KeyPressed4x'' }}'
        sequence: !input 'dimmer_up_4x'
      - conditions: '{{ attribute_id == ''KeyPressed5x'' }}'
        sequence: !input 'dimmer_up_5x'
  - conditions: '{{ scene_id == ''Scene 002'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_id == ''KeyPressed'' }}'
        sequence: !input 'dimmer_down_1x'
      - conditions: '{{ attribute_id == ''KeyPressed2x'' }}'
        sequence: !input 'dimmer_down_2x'
      - conditions: '{{ attribute_id == ''KeyPressed4x'' }}'
        sequence: !input 'dimmer_down_4x'
      - conditions: '{{ attribute_id == ''KeyPressed5x'' }}'
        sequence: !input 'dimmer_down_5x'
  - conditions: '{{ scene_id == ''Scene 003'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_id == ''KeyPressed'' }}'
        sequence: !input 'relay_1x'
      - conditions: '{{ attribute_id == ''KeyPressed2x'' }}'
        sequence: !input 'relay_2x'
      - conditions: '{{ attribute_id == ''KeyPressed4x'' }}'
        sequence: !input 'relay_4x'
      - conditions: '{{ attribute_id == ''KeyPressed5x'' }}'
        sequence: !input 'relay_5x'
