input_boolean:
  enable_climate_air:
    name: Enable Air

automation:
  - alias: "Climate_Air_0600_Weekday"
    initial_state: False
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.cooling
          temperature: 85
          operation_mode: 'Cool'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  - alias: "Climate_Air_0600_Weekend"
    initial_state: False
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.cooling
          temperature: 79
          operation_mode: 'Cool'
    condition:
      condition: time
      weekday:
        - sat
        - sun

  - alias: "Climate_Air_1600"
    initial_state: False
    trigger:
      platform: time
      at: "16:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.cooling
          temperature: 79
          operation_mode: 'Cool'

  - alias: "Climate_Air_2200"
    initial_state: False
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.cooling
          temperature: 76
          operation_mode: 'Cool'

  - alias: "Climate Air Enabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_air
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: group.ClimateAutomationAir
      - service: climate.set_operation_mode
        data:
          entity_id: climate.cooling
          operation_mode: 'Cool'
      - service: climate.set_temperature
        data:
          entity_id: climate.cooling
          temperature: 76
      - service: climate.set_fan_mode
        data:
          entity_id: climate.cooling
          fan_mode: 'Auto Low'

  - alias: "Climate Disabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_air
      to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: group.ClimateAutomationAir
      - service: climate.set_operation_mode
        data:
          entity_id: climate.cooling
          operation_mode: 'Off'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.cooling
          fan_mode: 'Auto Low'

group:
  ClimateAutomationAir:
    name: Climate Automation Air
    view: no
    entities:
      - automation.Climate_Air_0600_Weekday
      - automation.Climate_Air_0600_Weekend
      - automation.Climate_Air_1600
      - automation.Climate_Air_2200

