climate:
  - platform: zwave

input_boolean:
  enable_climate_heat:
    name: Enable Heat
  enable_climate_air:
    name: Enable Air

automation:
  - alias: "Climate_0600_Weekday"
    initial_state: True
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 68
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 85

    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  - alias: "Climate_0800_Weekday"
    initial_state: True
    trigger:
      platform: time
      at: "08:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 62
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  - alias: "Climate_0700_Weekend"
    initial_state: True
    trigger:
      platform: time
      at: "07:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 69
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 79
    condition:
      condition: time
      weekday:
        - sat
        - sun

  - alias: "Climate_1600"
    initial_state: True
    trigger:
      platform: time
      at: "16:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 69
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 79

  - alias: "Climate_2000"
    initial_state: True
    trigger:
      platform: time
      at: "20:00:00"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 62
      - service: climate.set_temperature
        data:
          entity_id: climate.central
          temperature: 76

  - alias: "Climate Heat Enabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_heat
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.enable_climate_air
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.central
          hvac_mode: 'heat'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.central
          fan_mode: 'auto'

  - alias: "Climate Heat Disabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_heat
      to: 'off'
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.central
          hvac_mode: 'off'

  - alias: "Climate Air Enabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_air
      to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.enable_climate_heat
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.central
          hvac_mode: 'cool'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.central
          fan_mode: 'auto'

  - alias: "Climate Air Disabled"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.enable_climate_air
      to: 'off'
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.central
          hvac_mode: 'off'

