group:
  fish:
    name: Fish Tank
    entities:
      - sensor.fish_temperature
      - switch.smart_strip_switch_1
      - switch.smart_strip_switch_2
      - switch.smart_strip_switch_3
      - switch.smart_strip_switch_4

# 1 = light, 2 = heater, 3 = UV

# https://www.home-assistant.io/docs/automation/trigger/

automation:
  - alias: "Turn on Fish Heater if cold"
    initial_state: True
    trigger:
       platform: template
       value_template: "{% if states.sensor.fish_temperature.state | float < 72.0 %} true {% endif %}"
    action:
      service: homeassistant.turn_on
      entity_id: switch.smart_strip_switch_2

  - alias: "Turn off Fish Heater if hot"
    initial_state: True
    trigger:
       platform: template
       value_template: "{% if states.sensor.fish_temperature.state | float > 75.0 %} true {% endif %}"
    action:
      service: homeassistant.turn_off
      entity_id: switch.smart_strip_switch_2

