timer:
  kid_music:
    duration: '00:05:00'

automation:
  - alias: "Kid motion ends"
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.kid_motion
      to: 'off'
    action:
      - service: timer.start
        entity_id: timer.kid_music
  - alias: "Kid motion starts"
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.kid_motion
      to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kid_music
  - alias: "Kid music timer ends"
    initial_state: True
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kid_music
    action:
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.sonos_kid
          sleep_time: 0

