# Function:  automatically turn on fan and increase speed depending on temperature
# adapted from https://selfhostedhome.com/automating-a-multi-speed-ceiling-fan-with-home-assistant/


climate:
  - platform: generic_thermostat
    name: Master Bedroom
    heater: switch.master_bedroom_thermostat_switch
    target_sensor: sensor.master_bedroom_temperature
    ac_mode: true
    target_temp: 74
    initial_hvac_mode: cool
    cold_tolerance: 1.0
    hot_tolerance: -1.0
    min_cycle_duration:
      seconds: 30

# Extract the set temperature from the generic thermostat from the master bedroom
sensor:
  platform: template
  sensors:
    master_bedroom_temperature_target:
      friendly_name: "Master Bedroom Target Temperature"
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.master_bedroom', 'temperature') }}"

# Switch used by master bedroom thermostat to turn on and off the fan
switch: 
  platform: template
  switches:
    master_bedroom_thermostat_switch:
      value_template:  "{{ is_state('automation.master_bedroom_fan_turn_on', 'on') }}"
      turn_on:
        service: automation.turn_on
        entity_id: automation.master_bedroom_fan_turn_on
      turn_off:
        - service: automation.turn_off
          entity_id: automation.master_bedroom_fan_turn_on
        - service: fan.turn_off
          entity_id: fan.master_fan_level

automation:
  alias: Master Bedroom Fan Turn On
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.master_bedroom_temperature
    - platform: state
      entity_id: sensor.master_bedroom_temperature_target
  condition:
    - condition: state
      entity_id: timer.master_bedroom_fan_cooldown
      state: 'idle'
  action:
    - service: fan.turn_on
      entity_id: fan.master_fan_level
      data_template:
          percentage: >-
            {% if (((states('sensor.master_bedroom_temperature_target') | float) - (states('sensor.master_bedroom_temperature') | float))) >= 1.0 %}
              33
            {% elif (((states('sensor.master_bedroom_temperature_target') | float) - (states('sensor.master_bedroom_temperature') | float))) <= -3.0 %}
              100
            {% else %}
              66
            {% endif %}
    - service: timer.start
      entity_id: timer.master_bedroom_fan_cooldown

# Timer used to control how often the speed of the office fan is updated
timer:
  master_bedroom_fan_cooldown:
    name: "Master Bedroom Fan Cooldown"
    duration: '00:05:00'
