binary_sensor:
  - platform: template
    sensors: 
      master_bedroom_motion:
        friendly_name: "Master Bedroom Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.master_bedroom_sensor_burglar', '8') }}"

