binary_sensor:
  - platform: template
    sensors: 
      master_bath_motion:
        friendly_name: "Master Bath Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.master_bath_burglar', '8') }}"
      master_bath_toilet_motion:
        friendly_name: "Master Bath Toilet Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.master_bath_toilet_burglar', '8') }}"

