binary_sensor:
  - platform: template
    sensors: 
      melanie_motion:
        friendly_name: "Melanie Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.melanie_dimmer_burglar', '8') }}"

