# rain delay

input_boolean:
  rain_delay:
    name: Rain Delay
    icon: mdi:water

timer:
  rain_delay:
    duration: '96:00:00'

automation:
  - alias: "Rain Delay manually triggered"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.rain_delay
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.rain_delay

  - alias: "Rain Delay timer ends"
    initial_state: True
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.rain_delay
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.rain_delay

