automation:
  - alias: "AtMidnight"
    initial_state: True
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.AtMidnight
  - alias: "At0630"
    initial_state: True
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: scene.turn_on
      entity_id: scene.At0630
  - alias: "AtNoon"
    initial_state: True
    trigger:
      platform: time
      at: '12:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.AtNoon
  - alias: "At4PM"
    initial_state: True
    trigger:
      platform: time
      at: '16:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.At4PM
  - alias: "At8PM"
    initial_state: True
    trigger:
      platform: time
      at: '20:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.At8PM
  - alias: "At9PM"
    initial_state: True
    trigger:
      platform: time
      at: '21:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.At9PM
  - alias: "Weekend Internet"
    initial_state: True
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: homeassistant.turn_on
      entity_id: group.internet
    condition:
      condition: time
      weekday:
        - sat
        - sun

scene:
  - name: "AtMidnight"
    entities:
      switch.piano_outlet_switch: off
      switch.smart_strip_switch_1: off #fish light
#      switch.master_bath_toilet_plug: off
      group.garage: off
  - name: "AtNoon"
    entities:
      switch.piano_outlet_switch: off
      switch.smart_strip_switch_1: off #fish light
      group.internet: on
  - name: "At4PM"
    entities:
      switch.piano_outlet_switch: off
#      switch.smart_strip_switch_1: off #fish light
      switch.smart_strip_switch_2: off # fish heater
  - name: "At8PM"
    entities:
      group.internet: off
  - name: "At9PM"
    entities:
      switch.smart_strip_switch_1: off #fish light
#      switch.smart_strip_switch_2: on # fish heater
      group.internet: off
  - name: InternetOn
    entities:
      switch.ipad_internet: on
      switch.melanie_internet: on
  - name: "At0630"
    entities:
      switch.master_bath_toilet_plug: on
      switch.water_heater_outlet: on
