automation:
  - alias: "AtMidnight"
    initial_state: True
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.AtMidnight
  - alias: "AtNoon"
    initial_state: True
    trigger:
      platform: time
      at: '12:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.AtNoon
  - alias: "At4PM"
    initial_state: True
    trigger:
      platform: time
      at: '16:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.At4PM
  - alias: "At9PM"
    initial_state: True
    trigger:
      platform: time
      at: '21:00:00'
    action:
      service: scene.turn_on
      entity_id: scene.At9PM
  - alias: "Weekend Internet"
    initial_state: True
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: homeassistant.turn_on
      entity_id: group.internet
    condition:
      condition: time
      weekday:
        - sat
        - sun

scene:
  - name: "AtMidnight"
    entities:
      switch.piano_outlet_switch: off
      switch.smart_strip_switch_2: off #fish light
      switch.garage_lights_switch_1: off
      switch.garage_lights_switch_2: off
      switch.garage_lights_switch_3: off
  - name: "AtNoon"
    entities:
      switch.piano_outlet_switch: off
      switch.smart_strip_switch_2: off #fish light
#      switch.ipad_internet: on
#      switch.melanie_internet: on
      group.internet: on
  - name: "At4PM"
    entities:
      switch.piano_outlet_switch: off
#      switch.smart_strip_switch_2: off #fish light
      switch.smart_strip_switch_3: off # fish heater
  - name: "At9PM"
    entities:
      switch.smart_strip_switch_2: off #fish light
#      switch.smart_strip_switch_3: on # fish heater
#      switch.ipad_internet: off
#      switch.melanie_internet: off
      group.internet: off
  - name: InternetOn
    entities:
      switch.ipad_internet: on
      switch.melanie_internet: on
