#   Lawn Watering
#


automation:
  - alias: "Water Plants"
    initial_state: True
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: scene.turn_on
      entity_id: scene.WaterPlants
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - wed
            - sat
        - condition: state
          entity_id: input_boolean.rain_delay
          state: 'off'
  - alias: "Water Front Lawn"
    initial_state: True
    trigger:
      platform: time
      at: '06:32:00'
    action:
      service: scene.turn_on
      entity_id: scene.WaterLawn
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - wed
            - sat
        - condition: state
          entity_id: input_boolean.rain_delay
          state: 'off'
  - alias: "Stop All Watering"
    initial_state: True
    trigger:
      platform: time
      at: '06:40:00'
    action:
      service: scene.turn_on
      entity_id: scene.StopAllWater

scene:
  - name: "WaterLawn"
    entities:
      switch.front_lawn_switch: on
  - name: "WaterPlants"
    entities:
      switch.side_drip_switch: on
      switch.back_drip_switch: on
      switch.front_drip_switch: on
  - name: "StopAllWater"
    entities:
      switch.side_drip_switch: off
      switch.back_drip_switch: off
      switch.front_lawn_switch: off
      switch.front_drip_switch: off

group:
  sprinklers:
    name: Sprinklers
    view: no
    entities:
      - switch.back_drip_switch
      - switch.side_drip_switch
      - switch.front_drip_switch
      - switch.front_lawn_switch
      - input_boolean.rain_delay
      - scene.WaterPlants
      - scene.WaterLawn
      - scene.StopAllWater

