#   Lawn Watering
#


automation:
  - alias: "Water Plants"
    initial_state: True
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: scene.turn_on
      entity_id: scene.WaterPlants
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - wed
            - sat
        - condition: state
          entity_id: input_boolean.rain_delay
          state: 'off'
  - alias: "Water Front Lawn"
    initial_state: True
    trigger:
      platform: time
      at: '06:32:00'
    action:
      service: scene.turn_on
      entity_id: scene.WaterLawn
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - wed
            - sat
        - condition: state
          entity_id: input_boolean.rain_delay
          state: 'off'
  - alias: "Stop All Watering"
    initial_state: True
    trigger:
      platform: time
      at: '06:40:00'
    action:
      service: scene.turn_on
      entity_id: scene.StopAllWater

  - alias: "Weekly Soaking"
    initial_state: True
    trigger:
      platform: time
      at: '07:00:00'
    action:
      service: switch.turn_on
      entity_id: switch.back_drip_switch
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
        - condition: state
          entity_id: input_boolean.rain_delay
          state: 'off'

  - alias: "Stop Weekly Soaking"
    initial_state: True
    trigger:
      platform: time
      at: '07:55:00'
    action:
      service: scene.turn_on
      entity_id: scene.StopAllWater

scene:
  - name: "WaterLawn"
    entities:
      switch.front_lawn: on
  - name: "WaterPlants"
    entities:
      switch.side_drip_switch: on
      switch.back_drip_switch: on
      switch.front_drip: on
  - name: "StopAllWater"
    entities:
      switch.side_drip_switch: off
      switch.back_drip_switch: off
      switch.front_lawn: off
      switch.front_drip: off
      switch.water_heater_outlet: off

group:
  sprinklers:
    name: Sprinklers
    view: no
    entities:
      - switch.back_drip_switch
      - switch.side_drip_switch
      - switch.front_drip
      - switch.front_lawn
