# Weather
weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

# Weather prediction
sensor:
  - platform: yr
  - platform: openweathermap
    api_key: !secret owm_api_key
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - clouds
      - rain

